@@include('module/menu.js')
@@include('module/modal.js')
@@include('module/filters.js')
@@include('module/scroll-horizontal.js')
@@include('module/scroll-vertical.js')
@@include('module/slider.js')
@@include('module/thermostat.js')
